Python is dynamically-typed: variable names can point to objects of any type.

This happens as variables are in fact pointers to objects. While objects have a specific type, variables can point to objects of any type. Below, we create a variable <code>x</code> and assign it (i.e., make it point) to an integer object with value 10. After that, we re-assign variable <code>x</code> so that it points to a string object.

In [ ]:
x = 10
x = 'hello'
x = "hello to show no differences between quote and double quote"

**Q1 : Can you concatenate the strings <code>a</code>, <code>b</code> and <code>c</code>?**

In [ ]:
a = "Name name is"
b = " R2D2"
c = "."

In [ ]:
#Solution to Q1


**Q2: Can you generete a string equal to x but with all characters in upper case?**

*Remember how to use Tab to auto-complete and check methods available to strings with x.*

In [ ]:
# Solution to Q2
x.upper()

**Q3: Can you split string x given words separated by spaces?**

In [ ]:
# Solution to Q3


['hello', 'to', 'show', 'no', 'differences', 'between', 'quote', 'and', 'double', 'quote']


**Q4: Can you repeat string <code>b</code> 10 times using a maximum of 3 characters?**

In [ ]:
# Solution to Q5
b = 'CMP7005'

<h1><center> Part I: Lists </center></h1>

In [ ]:
fruits = ['orange', 'apple', 'pear', 'banana', 'kiwi', 'apple', 'banana']
fruits[4]

In [ ]:
fruits[2:5]

In [ ]:
fruits.count('apple')

In [ ]:
fruits.index('banana')

In [ ]:
'apple' in fruits

In [ ]:
fruits.sort()
fruits

In [ ]:
len(fruits)

In [ ]:
fruits += [100]
fruits

**Q1: Can you work out how to insert a new object ('strawberry') in the below defined position in the list?**

In [ ]:
# Solution to Q1


['apple',
 'apple',
 'banana',
 'strawberry',
 'banana',
 'kiwi',
 'orange',
 'pear',
 100]

**Q2: Indexing: Can you write code to select elements of x from the 3rd to the second-last element (inclusive)?**

In [1]:
# Solution to Q2:
x = [1, 2, 3, 4, 5, 6, 7, 8] # say x is the given list

**Q3: Indexing: Can you write code to select elements of x in even positions (0, 2, 4, 6 ...)?**

In [ ]:
# Solution to Q3:
x = [1, 2, 3, 4, 5, 6, 7, 8] # say x is the given list

In [ ]:
x[1:9:2] # finding even numbers in the list

[2, 4, 6, 8]

**Q4: Indexing: Can you write code to select elements of x in odd positions (1, 3, 5...) in reverse order?**

In [ ]:
# Solution to Q4:
x = [1, 2, 3, 4, 5, 6, 7, 8] # say x is the given list


In [ ]:
x[-2:-9:-2] # finding the odd numbers in the list

[7, 5, 3, 1]

**Q5: Write code that prints 'a not contained in x' if <code>a</code> is not contained in <code>x</code>.**

In [ ]:
#Given the following list
x = [1, 2, 3, 4, 5, 6, 7, 8]
a = 6.2

In [ ]:
# Solution to Q4:


a not contained in x


<h2><center> Tuple </center></h2>

Ordered and **immutable** collection. Values within (square brackets) and comma-separated.

In [ ]:
t = (1,2,3)
t[2] = 5

TypeError: 'tuple' object does not support item assignment

**Q1: The previous cell should generate a TypeError. Can you explain why? Can you create a list with the same values as <code>t</code> and assign 5 to position 2 of the newly created list?**

In [ ]:
#Soluton to Q8:

# Error as t is a Tuple and Tuples are immutable
# A tuple offers a guarantee that a particular collection of objects will remain fixed

l = list(t)
l[2] = 5
l

<h2><center> Dictionaries </center></h2>

Dictionaries play a key role in Python and (as we will see in future labs) in Pandas.

Dictionaries are **mappings between key and values**.

In [ ]:
tel = {'jack': 4098, 'mary': 4139}
tel['guido'] = 4127
tel

In [ ]:
tel['jack']

In [ ]:
tel.keys()

In [ ]:
'guido' in tel
True

<h2><center>Sets</center></h2>

**Unordered** collections of **unique** items. Values within {curly brackets} and comma-separated. You can apply well-known set functions: union, intersection...

In [3]:
primes = {2, 3, 5, 7}
odds = set(range(1,10,2))
odds

{1, 3, 5, 7, 9}

In [ ]:
primes | odds

In [ ]:
primes & odds

In [ ]:
odds - primes

**Q1: Can you write 1-line of code to count the number of integers from 0 to 10 that are prime and even?**

In [ ]:
# Solution Q1:


<h2><center> Arrays </center></h2>

In [ ]:
# Create a NumPy array from a Python list:
import numpy as np
list_of_numbers = [10,11,12,13,14,15,16,17,18]


In [ ]:
# Create a NumPy array with the NumPy method np.arange between 10-19



array([10, 11, 12, 13, 14, 15, 16, 17, 18])

In [ ]:
print(numpy_array_of_numbers.shape,another_numpy_array.shape)

(9,)


**Q1: Can you make a numpy array of only even numbers between 10 and 20 (inclusive), without using a loop?**

In [ ]:
# Solution to Q1


array([10, 12, 14, 16, 18, 20])

<h2><center> Indexing and slicing </center></h2>

In [ ]:
yet_another_numpy_array = np.array([20,21,22,23,24,25,26,27,28,29])
yet_another_numpy_array

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [ ]:
yet_another_numpy_array[5]

In [ ]:
yet_another_numpy_array[3:]

In [ ]:
yet_another_numpy_array[:-2]

In [ ]:
yet_another_numpy_array[[True,True,True,True,False,False,False,False,False,False]] #boolean array as mask

In [ ]:
yet_another_numpy_array[yet_another_numpy_array > 24] #boolean array as mask

In [ ]:
yet_another_numpy_array[[0,4,5]] #fancy indexing

**Q2: How would you select only values between the "4th from last" to the "2nd from last" entries of this array?**

In [ ]:
#Solution to Q2



array([26, 27])

In [ ]:
array1 = np.array([[["John", "Ron", "Sean"],
                  ["Margaret", "Rachel", "Jim"],
                  ["Angel", "Joey", "Tom"]],

                 [["Max", "Maxine", "Richard"],
                  ["Barton ", "Flynn", "Simon"],
                  ["Bob", "Leo", "Kimn"]],

                 [["Wayne", "Sarah", "Lucy"],
                  ["Lucy", "Kurtis", "Yu"],
                  ["Jack", "Lex", "Alex"]]])
print(array1)

[[['John' 'Ron' 'Sean']
  ['Margaret' 'Rachel' 'Jim']
  ['Angel' 'Joey' 'Tom']]

 [['Max' 'Maxine' 'Richard']
  ['Barton ' 'Flynn' 'Simon']
  ['Bob' 'Leo' 'Kimn']]

 [['Wayne' 'Sarah' 'Lucy']
  ['Lucy' 'Kurtis' 'Yu']
  ['Jack' 'Lex' 'Alex']]]


In [ ]:
array1.shape

In [ ]:
array1.size

**General Access Syntax:** array1[block_index][row_index][column_index]


In [ ]:
array1 = np.array([[["John", "Ron", "Sean"],
                  ["Margaret", "Rachel", "Jim"],
                  ["Angel", "Joey", "Tom"]],

                 [["Max", "Maxine", "Richard"],
                  ["Barton ", "Flynn", "Simon"],
                  ["Bob", "Leo", "Kimn"]],

                 [["Wayne", "Sarah", "Lucy"],
                  ["Lucy", "Kurtis", "Yu"],
                  ["Jack", "Lex", "Alex"]]])
print(array1)

[[['John' 'Ron' 'Sean']
  ['Margaret' 'Rachel' 'Jim']
  ['Angel' 'Joey' 'Tom']]

 [['Max' 'Maxine' 'Richard']
  ['Barton ' 'Flynn' 'Simon']
  ['Bob' 'Leo' 'Kimn']]

 [['Wayne' 'Sarah' 'Lucy']
  ['Lucy' 'Kurtis' 'Yu']
  ['Jack' 'Lex' 'Alex']]]


In [ ]:
array1.shape

In [ ]:
array1.size

**Accessing Individual element**

In [ ]:
# First element of the first block
print(array1[0][0][0])

# Middle element of the second row in the second block
print(array1[1][1][1])

#Last element of the last block
print(array1[2][2][2])


**Accessing Entire Rows**

In [ ]:
# Entire first row of the first block
print(array1[0][0])

# Entire second row of the third block
print(array1[2][1])

**Accessing Entire Blocks**

In [ ]:
#Entire third block:
print(array1 [2])
print(array1[0])


**Slicing the Array**

In [ ]:
#Access the first column of each row from the third block:
array1[2, :, 0]

In [ ]:
# Access all names from the second column of each row across all blocks:
array1[:, :, 1]

**Fancy Indexing:**

In [ ]:
#You can also access specific elements from different locations using a list of indices.
array1[[0, 1], [0, 1], [0, 1]]

**Q3: How would you select only values of the last row starting from Wayne up to Alez?**

In [ ]:
#Solution to Q3


['Barton ' 'Flynn' 'Simon']


**Q4: How would you select Middle column, all rows, but don't flatten; keep matrix shape**

In [ ]:
#Solution to Q4
# When a list is used for choosing the column, the dimension is kept


[[['Margaret' 'Rachel' 'Jim']]

 [['Barton ' 'Flynn' 'Simon']]

 [['Lucy' 'Kurtis' 'Yu']]]


### switch the [row,column]

In [ ]:
a_numpy_2d_array = np.array([[11,12],[13,14]])
a_numpy_2d_array

array([[11, 12],
       [13, 14]])

In [ ]:
a_numpy_2d_array[:,0]

array([11, 13])

**Q5: Can you switch the [row,column] indices on this array?**

In [ ]:
#Solution to Q5


[[11 13]
 [12 14]]
[[11 13]
 [12 14]]


<h2><center> Reshaping Arrays </center></h2>

In [ ]:
numpy_digits_array = np.arange(0,9)
print(numpy_digits_array, " Shape: ", numpy_digits_array.shape)

[0 1 2 3 4 5 6 7 8]  Shape:  (9,)


In [ ]:
numpy_digits_array_2D = numpy_digits_array.reshape([3,3])
print(numpy_digits_array_2D, " Shape: ", numpy_digits_array_2D.shape)

[[0 1 2]
 [3 4 5]
 [6 7 8]]  Shape:  (3, 3)


In [ ]:
numpy_digits_array_2D_back_to_1D = numpy_digits_array_2D.reshape(-1)
print(numpy_digits_array_2D_back_to_1D, " Shape: ", numpy_digits_array_2D_back_to_1D.shape)

[0 1 2 3 4 5 6 7 8]  Shape:  (9,)


<h2><center> Arithmetic </center></h2>

In [ ]:
a = np.array([[10,11],[12,13]])
b = np.array([[1,-1],[-1,1]])
print("a:\n", a)
print("b:\n", b)

a:
 [[10 11]
 [12 13]]
b:
 [[ 1 -1]
 [-1  1]]


In [ ]:
print("a*b:\n", a*b)
print("a+b:\n", a+b)

In [ ]:
print("Matrix multiplication of a and b:\n",np.matmul(a,b))

In [ ]:
np.sum(a)

46

In [ ]:
print(a)
print("Sum all entries: ", np.sum(a))
print("Sum along lines: ", np.sum(a, axis=1))
print("Sum along columns: ", np.sum(a, axis=0))

#axis: the dimension of the array that will be colapsed

**Q7: Axis are important: Can you get the maximum over columns of these matrices? And the minimum over lines?**

In [2]:
import numpy as np
a_numpy_2d_array = np.array([[11,12],[13,14]])
a_numpy_2d_array

array([[11, 12],
       [13, 14]])

In [ ]:
# Solution to Q7



Max along lines:  [11 13]
Min along columns:  [10 11]


<h1><center> Broadcasting </center></h1>

In [ ]:
a = np.array([2.0, 4.0, 6.0])
b = np.array([7.0, 8.0, 9.0, 10.0])
print(a,"  ",b)

[2. 4. 6.]    [ 7.  8.  9. 10.]


In [ ]:
a+b

# Error? Understand why...

ValueError: operands could not be broadcast together with shapes (3,) (4,) 