<a href="https://colab.research.google.com/github/gihantha-sanjana/Programming-for-Data-Analysis/blob/main/Week2_Workshop1_solution.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Python is dynamically-typed: variable names can point to objects of any type.

This happens as variables are in fact pointers to objects. While objects have a specific type, variables can point to objects of any type. Below, we create a variable <code>x</code> and assign it (i.e., make it point) to an integer object with value 10. After that, we re-assign variable <code>x</code> so that it points to a string object.

In [ ]:
x = 10
x = 'hello'
x = "hello to show no differences between quote and double quote"

**Q1 : Can you concatenate the strings <code>a</code>, <code>b</code> and <code>c</code>?**

In [ ]:
a = "Name name is"
b = " R2D2"
c = "."

In [ ]:
#Solution to Q1
a + b + c

**Q2: Can you generete a string equal to x but with all characters in upper case?**

*Remember how to use Tab to auto-complete and check methods available to strings with x.*

In [ ]:
# Solution to Q2
#Define the string
x = "hello to show no differences between quote and double quote"

# Split the string into words
words = x.upper()

# Print the resulting list of words
print(words)

**Q3: Can you split string x given words separated by spaces?**

In [ ]:
# Solution to Q3
#Define the string
x = "hello to show no differences between quote and double quote"

# Split the string into words
words = x.split()

# Print the resulting list of words
print(words)

['hello', 'to', 'show', 'no', 'differences', 'between', 'quote', 'and', 'double', 'quote']


**Q4: Can you repeat string <code>b</code> 10 times using a maximum of 3 characters?**

In [ ]:
# Solution to Q4
b = 'CMP7005'
result = b * 10
print(result)


CMP7005CMP7005CMP7005CMP7005CMP7005CMP7005CMP7005CMP7005CMP7005CMP7005


<h1><center> Part I: Lists </center></h1>

In [ ]:
fruits = ['orange', 'apple', 'pear', 'banana', 'kiwi', 'apple', 'banana']
fruits[4]

'kiwi'

In [ ]:
fruits[2:5]

['pear', 'banana', 'kiwi']

In [ ]:
fruits.count('apple')

2

In [ ]:
fruits.index('banana')

3

In [ ]:
'apple' in fruits

True

In [ ]:
fruits.sort()
fruits

['apple', 'apple', 'banana', 'banana', 'kiwi', 'orange', 'pear']

In [ ]:
len(fruits)

7

In [ ]:
fruits += [100]
fruits

['apple', 'apple', 'banana', 'banana', 'kiwi', 'orange', 'pear', 100]

**Can you work out how to insert a new object ('strawberry') in the middle of the above list?**

In [ ]:
# Solution to Q1
fruits.insert(3, 'strawberry')
fruits

['apple',
 'apple',
 'banana',
 'strawberry',
 'banana',
 'kiwi',
 'orange',
 'pear',
 100]

**Q2: Indexing: Can you write code to select elements of x from the 3rd to the second-last element (inclusive)?**

In [ ]:
# Solution to Q2:
x = [1, 2, 3, 4, 5, 6, 7, 8] # say x is the given list
x[2:-1]


[3, 4, 5, 6, 7]

In [ ]:
x[2:7]

[3, 4, 5, 6, 7]

**Q3: Indexing: Can you write code to select elements of x in even positions (0, 2, 4, 6 ...)?**

In [ ]:
# Solution to Q3:
x = [1, 2, 3, 4, 5, 6, 7, 8] # say x is the given list
x[::2]

[1, 3, 5, 7]

In [ ]:
x[0:7:2]

[1, 3, 5, 7]

In [ ]:
x[1:9:2] # finding even numbers in the list

[2, 4, 6, 8]

**Q4: Indexing: Can you write code to select elements of x in odd positions (1, 3, 5...) in reverse order?**

In [ ]:
# Solution to Q4:
x = [1, 2, 3, 4, 5, 6, 7, 8] # say x is the given list
x[-1:-8:-2]


[8, 6, 4, 2]

In [ ]:
x[::-2]

[8, 6, 4, 2]

In [ ]:
x[-2:-9:-2] # finding the odd numbers in the list

[7, 5, 3, 1]

**Q5: Write code that prints 'a not contained in x' if <code>a</code> is not contained in <code>x</code>.**

In [ ]:
#Given the following list
x = [1, 2, 3, 4, 5, 6, 7, 8]
a = 6.2

In [ ]:
# Solution to Q5:

if a not in x:
    print('a not contained in x')

a not contained in x


<h2><center> Tuple </center></h2>

Ordered and **immutable** collection. Values within (square brackets) and comma-separated.

In [ ]:
t = (1,2,3)
t[2] = 5

TypeError: 'tuple' object does not support item assignment

**Q1: The previous cell should generate a TypeError. Can you explain why? Can you create a list with the same values as <code>t</code> and assign 5 to position 2 of the newly created list?**

In [ ]:
#Soluton to Q8:

# Error as t is a Tuple and Tuples are immutable
# A tuple offers a guarantee that a particular collection of objects will remain fixed

l = list(t)
l[2] = 5
l

[1, 2, 5]

<h2><center> Dictionaries </center></h2>

Dictionaries play a key role in Python and (as we will see in future labs) in Pandas.

Dictionaries are **mappings between key and values**.

In [ ]:
tel = {'jack': 4098, 'mary': 4139}
tel['guido'] = 4127
tel

{'jack': 4098, 'mary': 4139, 'guido': 4127}

In [ ]:
tel['jack']

4098

In [ ]:
tel.keys()

dict_keys(['jack', 'mary', 'guido'])

In [ ]:
'guido' in tel
True

True

<h2><center>Sets</center></h2>

**Unordered** collections of **unique** items. Values within {curly brackets} and comma-separated. You can apply well-known set functions: union, intersection...

In [ ]:
primes = {2, 3, 5, 7}
odds = set(range(1,10,2))
odds

{1, 3, 5, 7, 9}

In [ ]:
# This represents the union of two sets, primes and odds. It combines all unique elements from both sets. In Python, the union of sets can be done using the | operator.
primes | odds # (Union of two sets)

{1, 2, 3, 5, 7, 9}

In [ ]:
# This operation will give the elements that are present in both the primes and odds sets.
primes & odds # Intersection of two sets (elements common to both sets).

{3, 5, 7}

In [ ]:
odds - primes # Difference of two sets (elements in the first set but not in the second).

{1, 9}

**Q1: Can you write 1-line of code to count the number of integers from 0 to 10 that are prime and even?**

In [ ]:
# Solution Q1:

(set(range(10))-odds) & primes

{2}

<h2><center> Arrays </center></h2>

In [ ]:
# Create a NumPy array from a Python list:
import numpy as np
list_of_numbers = [10,11,12,13,14,15,16,17,18]
numpy_array_of_numbers = np.array(list_of_numbers)
print('\n the array from list is :',numpy_array_of_numbers)


 the array from list is : [10 11 12 13 14 15 16 17 18]


In [ ]:
# Create a NumPy array with the NumPy method np.arange

another_numpy_array = np.arange(10,19)
another_numpy_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18])

In [ ]:
print(numpy_array_of_numbers.shape, another_numpy_array.shape)

(9,) (9,)


**Q1: Can you make a numpy array of only even numbers between 10 and 20 (inclusive), without using a loop?**

In [ ]:
# Solution to Q1
import numpy as np

numbers = np.arange(10, 21)
print(numbers)


[10 11 12 13 14 15 16 17 18 19 20]


In [ ]:
'''
np.arange(10, 21, 2):
start=10: The sequence will start at 10.
stop=21: The sequence will stop before reaching 21 (so it includes 20 but excludes 21).
step=2: This makes sure that only every second number (i.e., even numbers) is included in the array.

'''

numbers1 = np.arange(10,21,2)
print(numbers1)

[10 12 14 16 18 20]


<h2><center> Indexing and slicing </center></h2>

In [ ]:
yet_another_numpy_array = np.array([20,21,22,23,24,25,26,27,28,29])
yet_another_numpy_array

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [ ]:
yet_another_numpy_array[5]

25

In [ ]:
yet_another_numpy_array[3:]

array([23, 24, 25, 26, 27, 28, 29])

In [ ]:
yet_another_numpy_array[:-2]

array([20, 21, 22, 23, 24, 25, 26, 27])

In [ ]:
yet_another_numpy_array[[True,True,True,True,False,False,False,False,False,False]] #boolean array as mask

array([20, 21, 22, 23])

In [ ]:
yet_another_numpy_array[yet_another_numpy_array > 24] #boolean array as mask

array([25, 26, 27, 28, 29])

In [ ]:
yet_another_numpy_array[[0,4,5]] #fancy indexing

array([20, 24, 25])

**Q2: How would you select only values between the "4th from last" to the "2nd from last" entries of this array?**

In [ ]:
#Solution to Q2
yet_another_numpy_array[-4:-2]

**General Access Syntax:** array1[block_index][row_index][column_index]


In [ ]:
array1 = np.array([[["John", "Ron", "Sean"],
                  ["Margaret", "Rachel", "Jim"],
                  ["Angel", "Joey", "Tom"]],

                 [["Max", "Maxine", "Richard"],
                  ["Barton ", "Flynn", "Simon"],
                  ["Bob", "Leo", "Kimn"]],

                 [["Wayne", "Sarah", "Lucy"],
                  ["Lucy", "Kurtis", "Yu"],
                  ["Jack", "Lex", "Alex"]]])
print(array1)

[[['John' 'Ron' 'Sean']
  ['Margaret' 'Rachel' 'Jim']
  ['Angel' 'Joey' 'Tom']]

 [['Max' 'Maxine' 'Richard']
  ['Barton ' 'Flynn' 'Simon']
  ['Bob' 'Leo' 'Kimn']]

 [['Wayne' 'Sarah' 'Lucy']
  ['Lucy' 'Kurtis' 'Yu']
  ['Jack' 'Lex' 'Alex']]]


In [ ]:
array1.shape

(3, 3, 3)

In [ ]:
array1.size

27

### **Let's look at what happens with various slicing schemes**

In [ ]:
# First element of the first block
print(array1[0][0][0])

# Middle element of the second row in the second block
print(array1[1][1][1])

#Last element of the last block
print(array1[2][2][2])


John
Flynn
Alex


**Accessing Entire Rows**

In [ ]:
# Entire first row of the first block
print(array1[0][0])

# Entire second row of the third block
print(array1[2][1])

['John' 'Ron' 'Sean']
['Lucy' 'Kurtis' 'Yu']


**Accessing Entire Blocks**

In [ ]:
#Entire third block:
print(array1 [2])
print(array1[0])


[['Wayne' 'Sarah' 'Lucy']
 ['Lucy' 'Kurtis' 'Yu']
 ['Jack' 'Lex' 'Alex']]
[['John' 'Ron' 'Sean']
 ['Margaret' 'Rachel' 'Jim']
 ['Angel' 'Joey' 'Tom']]


**Slicing the Array**

In [ ]:
#Access the first column of each row from the third block:
array1[2, :, 0]

array(['Wayne', 'Lucy', 'Jack'], dtype='<U8')

In [ ]:
# Access all names from the second column of each row across all blocks:
array1[:, :, 1]

array([['Ron', 'Rachel', 'Joey'],
       ['Maxine', 'Flynn', 'Leo'],
       ['Sarah', 'Kurtis', 'Lex']], dtype='<U8')

**Fancy Indexing:**

In [ ]:
#You can also access specific elements from different locations using a list of indices.
array1[[0, 1], [0, 1], [0, 1]]

array(['John', 'Flynn'], dtype='<U8')

**Q4: How would you select Middle column, all rows, but don't flatten; keep matrix shape**

In [ ]:
#Solution to Q4
# When a list is used for choosing the column, the dimension is kept
print(array1[:, [1]])

[[['Margaret' 'Rachel' 'Jim']]

 [['Barton ' 'Flynn' 'Simon']]

 [['Lucy' 'Kurtis' 'Yu']]]


### switch the [row,column]

In [ ]:
a_numpy_2d_array = np.array([[11,12],[13,14]])
a_numpy_2d_array

array([[11, 12],
       [13, 14]])

In [ ]:
a_numpy_2d_array[1,0]

13

In [ ]:
a_numpy_2d_array[:,0]

array([11, 13])

**Q5: Can you switch the [row,column] indices on this array?**

In [ ]:
#Solution to Q5
print(np.transpose(a_numpy_2d_array))
print(a_numpy_2d_array.T)

[[11 13]
 [12 14]]
[[11 13]
 [12 14]]


In [ ]:
numpy_digits_array = np.arange(0,9)
print(numpy_digits_array, " Shape: ", numpy_digits_array.shape)

[0 1 2 3 4 5 6 7 8]  Shape:  (9,)


In [ ]:
numpy_digits_array_2D = numpy_digits_array.reshape([3,3])
print(numpy_digits_array_2D, " Shape: ", numpy_digits_array_2D.shape)

[[0 1 2]
 [3 4 5]
 [6 7 8]]  Shape:  (3, 3)


In [ ]:
numpy_digits_array_2D_back_to_1D = numpy_digits_array_2D.reshape(-1)
print(numpy_digits_array_2D_back_to_1D, " Shape: ", numpy_digits_array_2D_back_to_1D.shape)

[0 1 2 3 4 5 6 7 8]  Shape:  (9,)


<h2><center> Arithmetic </center></h2>

In [ ]:
a = np.array([[10,11],[12,13]])
b = np.array([[1,-1],[-1,1]])
print("a:\n", a)
print("b:\n", b)

a:
 [[10 11]
 [12 13]]
b:
 [[ 1 -1]
 [-1  1]]


In [ ]:
print("a*b:\n", a*b)
print("a+b:\n", a+b)

a*b:
 [[ 10 -11]
 [-12  13]]
a+b:
 [[11 10]
 [11 14]]


In [ ]:
print("Matrix multiplication of a and b:\n",np.matmul(a,b))

Matrix multiplication of a and b:
 [[-1  1]
 [-1  1]]


In [ ]:
np.sum(a)

46

In [ ]:
print(a)
print("Sum all entries: ", np.sum(a))
print("Sum along lines: ", np.sum(a, axis=1))
print("Sum along columns: ", np.sum(a, axis=0))

#axis: the dimension of the array that will be colapsed

[[10 11]
 [12 13]]
Sum all entries:  46
Sum along lines:  [21 25]
Sum along columns:  [22 24]


**Q7: Axis are important: Can you get the maximum over columns of these matrices? And the minimum over lines?**

In [ ]:
import numpy as np
a = np.array([[11,12],[13,14]])
a

array([[11, 12],
       [13, 14]])

In [ ]:
# Solution to Q7
print("Max along lines: ", np.max(a, axis=1))
print("Min along columns: ", np.min(a, axis=0))

Max along lines:  [12 14]
Min along columns:  [11 12]


<h1><center> Broadcasting </center></h1>

In [ ]:
a = np.array([2.0, 4.0, 6.0])
b = np.array([7.0, 8.0, 9.0, 10.0])
print(a,"  ",b)

[2. 4. 6.]    [ 7.  8.  9. 10.]


In [ ]:
a+b

# Error? Understand why...

ValueError: operands could not be broadcast together with shapes (3,) (4,) 